DROP TABLE IF EXISTS SONG;
DROP TABLE IF EXISTS ALBUM;
DROP TABLE IF EXISTS CONCERT;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS CONCERT_PLAYLIST;
DROP TABLE IF EXISTS SONG_GENRE;

CREATE TABLE ALBUM(
    ID INTEGER NOT NULL IDENTITY,
    TITLE VARCHAR(40) NOT NULL UNIQUE,
    RELEASE DATE NOT NULL,
    DESCRIPTION VARCHAR(5000),

    PRIMARY KEY (ID)
);
CREATE TABLE SONG(
    ID INTEGER NOT NULL IDENTITY,
    TITLE VARCHAR(40) NOT NULL UNIQUE,
    LENGTH DECIMAL(2,2) NOT NULL,
    GENRES VARCHAR(200) NOT NULL,
    FINISHED_RECORDING DATE NOT NULL,
    ALBUM_ID INTEGER NOT NULL,
    DESCRIPTION VARCHAR(5000),

    PRIMARY KEY (ID),
    FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM(ID)
);

CREATE TABLE CONCERT(
    ID INTEGER NOT NULL IDENTITY,
    NAME VARCHAR(40) NOT NULL UNIQUE,
    LOCATION VARCHAR(80) NOT NULL,
    DATE DATE NOT NULL,
    DESCRIPTION VARCHAR(5000),

    PRIMARY KEY (ID)
);

CREATE TABLE GENRE(
    ID INTEGER NOT NULL IDENTITY,
    NAME VARCHAR(20) NOT NULL UNIQUE,

    PRIMARY KEY(ID)
);

CREATE TABLE CONCERT_PLAYLIST(
    ID INTEGER NOT NULL IDENTITY,
    SONG_ID INTEGER NOT NULL,
    CONCERT_ID INTEGER NOT NULL,

    PRIMARY KEY(ID),
    FOREIGN KEY(SONG_ID) REFERENCES SONG(ID),
    FOREIGN KEY(CONCERT_ID) REFERENCES CONCERT(ID)
);

CREATE TABLE SONG_GENRE(
    ID INTEGER NOT NULL IDENTITY,
    SONG_ID INTEGER NOT NULL,
    GENRE_ID INTEGER NOT NULL,

    PRIMARY KEY(ID),
    FOREIGN KEY(SONG_ID) REFERENCES SONG(ID),
    FOREIGN KEY(GENRE_ID) REFERENCES GENRE(ID)
);

